from django.core.management.base import BaseCommand

from contest.models import Exhibition

ex_titles = ['Выставка Game junction / Игровое сопряжение ', 'Выставка Число как образ', 'Выставка Ограничение', 'Выставка «Затемнение»', 'Выставка Потапов-Бронштейн «Хроники изоляции»', 'Выставка «Простые вещи»', 'Выставка «На дне»', 'участвуют только в диджитал игре (нет площадки офлайн)', 'участвуют только в диджитал игре (нет площадки офлайн)', 'Виртуальная выставка и не-игра Notland!', 'Выставка Петра Кирюши «Сломанный куст»', 'Выставка объектов, инсталляций, видео-арта «Кровь с молоком to go»', 'Выставка Digital Legacy', 'Выставка Ау', 'Выставка «Myth or reality?»', 'Выставка «Неуловимые миры»', "One's mind", 'SEND NUDES', 'Выставка-инсталлция  Джейкоба Якубова Shadow of Adam', 'Выствка «Альтерглобализм»', 'ЛАБОРАТОРНАЯ ВЫСТАВКА СТУДЕНТОВ ШКОЛЫ РОДЧЕНКО и ВЫСТАВКА «IMMEVAL» ПОЛИНА РЫМАН', 'Персональная выставка Гоши Острецова «Подобие Подобному Подобного»', 'Выставка  российского медиахудожника Сержа Головача «Сопромат»', 'Выставка «Фотореализм в России»', 'участуют только онлайн (игра + маркет)', 'Коллекцию галереи ', 'Выставка Андрея Крисанова «В поисках ключей»', 'Групповая выставка «Тёмная сторона радуги»', 'Выставка «Курорты»', 'Выставка Марии Черепановой «Приключения одного сердца»']
ex_links = ['https://everart-weekend.ru/khodynka', 'https://everart-weekend.ru/vzm_a3', 'https://everart-weekend.ru/vzm_nagornaya', 'https://everart-weekend.ru/1112_gallery', 'https://everart-weekend.ru/pop_off_art', 'https://everart-weekend.ru/glaz_gallery', 'https://everart-weekend.ru/inart', '""', '""', '""', 'https://everart-weekend.ru/myth_gallery', 'https://everart-weekend.ru/didi_gallery', 'https://everart-weekend.ru/surface_lab_art', 'https://everart-weekend.ru/sam', 'https://everart-weekend.ru/wip', 'https://everart-weekend.ru/askeri_gallery', 'https://everart-weekend.ru/event_ones_mind_gallery', 'https://everart-weekend.ru/store_bar_gallery', 'https://everart-weekend.ru/who_i_am_gallery', 'https://everart-weekend.ru/vzm_belyaevo', 'https://everart-weekend.ru/vzm_peresvetov_pereulok', 'https://everart-weekend.ru/syntax_gallery', 'https://everart-weekend.ru/gum_red_line', 'https://everart-weekend.ru/fineart_gallery', '""', 'https://everart-weekend.ru/bis_art_gallery', 'https://everart-weekend.ru/kuryokhin_center', '""', 'https://everart-weekend.ru/pogodina_gallery', 'https://everart-weekend.ru/znachimoe_gallery']
ex_codes = ['JX8oftB64M', '0h1ESTvTcz', 'JoneyMP6tI', '43X6dUYw7H', 'NH4XPi6xOG', 'WdkXkKiYWo', '87lC9sqE1T', 'tZEAeNIp3P', 'tPdXJChIpf', 'xBu1QOMHJp', 'bOOpYdgV1Z', 'B6p9zchYOu', '6HlNbx62KH', 'rPr3aLgK46', 'xllW09Upru', 'e6OB1cBrkG', 'Sb1maf6xDw', 'Q8a3yFDeWY', 'gVeKdYxbmy', 'igMKFz1iva', 'HUg5zHoOGn', 'YGXbBPv1mr', '20wIkonLuo', 'NDIsIb5fwv', '4EYyRZCz0d', 'xscjKAVkad', 'DdlmWMeVVJ', 'Cqk1N11DQP', 'Ymsu5ay6ga', 'Lma407igwy']

class Command(BaseCommand):
    help = 'Генерация базы данных'

    def handle(self, *args, **kwargs):
        for i in range(30):
            exhib = Exhibition.objects.create(title=ex_titles[i], link=ex_links[i], code=ex_codes[i])
