# Generated by Django 3.1.1 on 2021-06-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exhibition',
            old_name='qr_code',
            new_name='code',
        ),
        migrations.AddField(
            model_name='exhibition',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
