# Generated by Django 3.1.1 on 2021-06-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20210628_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='num_visited',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
