# Generated by Django 3.1.1 on 2021-06-29 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_auto_20210628_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='num_visited',
            new_name='exhibitions_visited',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='is_winner',
            new_name='is_participant',
        ),
    ]
